name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  linux-min:
    name: Linux Min Config
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        compiler: [clang++-15, g++-12]
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - name: Install Dependencies
      # Boost must be installed only because the CMake version (3.12) can't
      # detect the installed Boost version (1.69)
      run: sudo apt-get update && sudo apt-get -y install ninja-build libboost-date-time-dev g++-multilib
    - name: Run tests with common Catch
      run: |
        cmake -G Ninja .
        cmake --build . -- test_hello-world
        cmake --build .
      env:
        CXX: ${{ matrix.compiler }}

  linux-latest:
    name: Linux Latest Config
    needs: [linux-min]
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        compiler: [clang++, g++]
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - name: Install Dependencies
      # Boost must be installed only because the CMake version (3.12) can't
      # detect the installed Boost version (1.69)
      run: sudo apt-get update && sudo apt-get -y install ninja-build libboost-date-time-dev
    - name: Run tests with common Catch
      if: matrix.compiler == 'g++'
      run: |
        cmake -G Ninja .
        cmake --build . -- test_hello-world
        cmake --build .
      env:
        CXX: ${{ matrix.compiler }}
    - name: Run tests without common Catch
      if: matrix.compiler == 'clang++'
      run: |
        cmake -G Ninja -DEXERCISM_COMMON_CATCH=OFF .
        cmake --build . -- test_hello-world
        cmake --build .
      env:
        CXX: ${{ matrix.compiler }}

  windows:
    name: Windows
    needs: [linux-min]
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - name: Run Tests
      shell: powershell
      # Delete the exercises that require Boost to avoid issues with Windows setup.
      run: |
        rm exercises/practice/gigasecond -r
        rm exercises/practice/meetup -r
        cmake .
        cmake --build . -- test_hello-world
        cmake --build .

  mac:
    name: MacOS
    needs: [linux-min]
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - name: Install Boost
      run: brew install boost
    - name: Run Tests
      run: |
        cmake .
        cmake --build . -- test_hello-world
        cmake --build .

